isce-framework/snaphu-py

.github/workflows/ci.yml
ci/min-reqs.txt
pyproject.toml

Add GitHub Actions workflows to install and test
* on Linux & macOS
* with the minimum supported versions of dependencies
* with & without optional dependencies (i.e. rasterio)
Bumps the minimum rasterio version to 1.2. Pip struggles to install older versions with Python 3.9 (our minimum Python version). Rasterio 1.2.0 has been around since Jan 2021, so I don't really have qualms about requiring at least that version.

Add basic build+test CI workflow

---

.github/workflows/ci.yml

Fix version tests in CI by fetching tags when checking out the repo so that setuptools_scm correctly infers the version syntax.

Fix version tests in CI

---

src/snaphu/_unwrap.py
test/test_unwrap.py

Closes #2
SNAPHU errors if the input interferogram contains NaN or infinity values, but NaN is commonly used as a fill value to represent invalid samples, which we want to mask out for purposes of unwrapping.
As @scottstanie reminded me, it's convenient for the Python wrapper to replace NaN values with zeros, since SNAPHU treats zero-magnitude samples as invalid (masked out).

Replace NaN values with zero

---

.github/workflows/ci.yml

If no version is specified, it doesn't install anything and just uses the system Python installation.
>[Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.](https://github.com/isce-framework/snaphu-py/actions/runs/7096568500/job/19315271192#step:3:10)

Specify minimum Python version for actions/setup-python

---

.github/codecov.yml
.github/workflows/ci.yml
src/snaphu/_unwrap.py

Add code coverage reporting via codecov. Coverage diffs are informational only -- drops in coverage don't cause checks to fail.

Add codecov reporting

---

src/snaphu/io/_raster.py
test/io/test_raster.py

Add the ability to set (when creating the Raster) and get the "nodata" value from Raster objects.
It seems most intuitive that the "nodata" value should have the same dtype as the Raster image data. However, due to underlying limitations in GDAL/rasterio[^1][^2], the nodata value must be a `float`, even if the raster is integer- or complex-valued.
[^1]: https://github.com/OSGeo/gdal/pull/808
[^2]: https://github.com/rasterio/rasterio/issues/1747

Add nodata attribute to Raster

---

src/snaphu/_unwrap.py
test/test_unwrap.py

Add a new option `regrow_conncomps` to `unwrap()`. When enabled, it will re-run SNAPHU after the initial unwrapping step to "regrow" the connected components. This is useful in tiled unwrapping mode to compute a new set of connected components that are not delimited by the tile boundaries.
This behavior is typically desirable when unwrapping in tiled mode, and the regrowing step seems to be pretty fast + doesn't require much memory compared with unwrapping, so this option will be enabled by default.
Thanks to @scottstanie for showing me this option in SNAPHU and testing it out.
This PR also removes the `SnaphuConfig` class that was a bit over-engineered and wasn't easily extendable to support some of the more esoteric SNAPHU configurations/modes.

Add an option (enabled by default) to regrow connected components in tiled mode

---

pyproject.toml

Update the `pyproject.toml` file to include some basic package metadata (maintainers, URLs, classifiers, etc.)
Since the SNAPHU source is included as a Git submodule, it's likely to be included in source and binary distributions of snaphu-py, so I opted to include info about its license in the package metadata in addition to the license of the Python wrapper. I'm not sure whether that's appropriate or not, but it seemed to be the most prudent strategy in the face of uncertainty.

Add package metadata to pyproject.toml

---

.github/workflows/cd.yml

Add a GHA workflow which triggers whenever a versioned tag is pushed. It will automatically draft a release using https://github.com/softprops/action-gh-release. Git archives of the repo \*and all of its submodules\* are generated using https://github.com/Kentzo/git-archive-all and uploaded as release artifacts (in both .zip and .tar.gz format).
This is intended as a workaround for https://github.com/dear-github/dear-github/issues/214. The archives generated by GitHub on each release do not include submodules. This is inconvenient for distributing via package repositories like PyPI and conda-forge, which typically prefer to fetch source tarballs from GitHub.

Automate upload of release source archives

---

.github/workflows/ci.yml
pyproject.toml

Add a CI job that runs on pull requests and pushes to main and executes the following steps:
* Build wheels for Linux & macOS x86_64, as well as Linux i686 and macOS ARM64 using [cibuildwheel](https://github.com/pypa/cibuildwheel)
* Run the test suite using generated wheels (except for macOS ARM64, which is cross-compiled)
* Lint wheels using [check-wheel-contents](https://github.com/jwodder/check-wheel-contents)
* Build an sdist and lint it using [`twine check`](https://twine.readthedocs.io/en/stable/#twine-check)
* Publish wheels & sdist to [TestPyPI](https://packaging.python.org/en/latest/guides/using-testpypi/)

Build wheels & sdists in CI

---

.github/release.yml

Configure the automatically-generated release notes to exclude contributions from @dependabot and @pre-commit-ci.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options

Ignore contributions by bots in release notes

---

.github/workflows/ci.yml

32-bit Linux binaries seem to be much slower than 64-bit binaries on GHA runners. In recent workflow runs, testing the 64-bit Linux wheels took [~30-45 seconds each](https://github.com/isce-framework/snaphu-py/actions/runs/7574041340/job/20627549981), whereas testing the 32-bit wheels took [~195-270 seconds each](https://github.com/isce-framework/snaphu-py/actions/runs/7574041340/job/20627551723).
I'm not really sure what would account for this large runtime discrepancy, but don't have any immediate plans to investigate since I doubt there's any real demand for 32-bit binaries among SNAPHU users.
Building & testing 32-bit wheels is currently a major bottleneck in CI workflows that include this step. So let's just disable them in our builds.

Don't build 32-bit wheels

---

.github/codecov.yml

If a PR modifies only some subset of these paths, Codecov should not produce a report. This should hopefully reduce notification spam a little bit.
https://docs.codecov.com/docs/ignoring-paths

Exclude some paths from Codecov scans

---

src/snaphu/_unwrap.py
test/test_unwrap.py

This PR adds `tile_cost_thresh` and `min_region_size` optional parameters to the `unwrap()` function. They map to the SNAPHU config parameters `TILECOSTTHRESH` and `MINREGIONSIZE`, respectively, and share the same default values as those parameters.
These options are potentially useful for controlling the size/number of connected components in tile mode. Even if connected component regrowing is enabled, the user may still wish to adjust these parameters in order improve the performance of the "secondary unwrapping" step. Decreasing the tile cost threshold and/or increasing the minimum region size may also help to avoid [unwrapping failures due to exceeding the max allowed number of secondary nodes/arcs](https://github.com/gmgunter/snaphu/blob/4b7ca6c08eec6b7e6a61d739237b8c182f0ce795/src/sn …

Expose `TILECOSTTHRESH` and `MINREGIONSIZE` parameters

---

.gitmodules

HTTPS links are more easily accessible for folks who haven't setup SSH keys with GitHub.

Replace submodule SSH URL with HTTPS URL

---

README.md

It's not clearly documented anywhere that the project contains Git submodules and therefore needs to be cloned with `--recursive` or `--recurse-submodules`. Let's address that by updating the installation instructions to cover the case of installing from a local clone.

Update instructions for installating from source

---

src/snaphu/_check.py
src/snaphu/_conncomp.py
src/snaphu/_unwrap.py
test/test_conncomp.py
test/test_unwrap.py

Refactor input validation checks to reduce copy/paste and improve coverage. The should be no functional changes (except for slightly different error messages).

Reduce code duplication in input validation checks

---

src/snaphu/_conncomp.py
src/snaphu/_unwrap.py
test/test_conncomp.py

Adds an optional argument `min_conncomp_frac` to the `unwrap()` and `grow_conncomps()` functions. It maps to the SNAPHU config parameter `MINCONNCOMPFRAC`, which controls the minimum possible size of a connected component as a fraction of the total tile size in pixels.

Expose `MINCONNCOMPFRAC` parameter

---

CMakeLists.txt
README.md

* Update CMake build script to forbid installation on Windows. This should hopefully provide a more meaningful error message for unsuspecting Windows users.
* Add a badge and FAQ entry to the README describing supported operating systems.

Clarify supported platforms in README and CMake scripts

---

.pre-commit-config.yaml
src/snaphu/io/__init__.pyi
test/io/test_raster.py

This PR supersedes #66. Refer to that PR for background.
The approach in the previous PR satisfied Pylance but ran into issues with Mypy. This PR instead tries to resolve the issue by including a typing stub (.pyi) file that exposes the Raster class for static analysis tools like Pylance and Mypy without affecting the runtime behavior.
The new approach seems to work well, except Mypy now complains about the new stub file conflicting with the existing .py file:
```
src/snaphu/io/__init__.pyi: error: Duplicate module named "snaphu.io" (also at "src/snaphu/io/__init__.py")
```
This seems to be related to the way that pre-commit passes arguments to Mypy. When running Mypy on a directory containing both .py and .pyi files, it runs fine. But when passing individual .py and .pyi files with …

Improve Pylance support for `Raster`

---

src/snaphu/_check.py
src/snaphu/_unwrap.py
test/test_unwrap.py

`KPARDPSI` and `KPERPDPSI` are SNAPHU config options that control the size of the sliding window used to estimate the local phase gradient when computing the cost functions. @vbrancat pointed out that it's sometimes useful to modify these parameters.
The two options are exposed as a pair of ints via a new keyword-only parameter `phase_grad_window` in the Python interface.
I'm open to feedback regarding the renaming -- up until now, parameter names have been mostly straightforward translations of the corresponding SNAPHU configuration options, but "KPARDPSI" and "KPERPDPSI" seem like especially poor public variable names to me.

Expose KPARDPSI and KPERPDPSI options

---

src/snaphu/_conncomp.py
src/snaphu/_unwrap.py
src/snaphu/_util.py
test/test_util.py

Previously, the library made extensive usage of memory-mapping to copy the contents of inputs & outputs to & from binary files for compatibility with the SNAPHU executable. Memory-mapping is convenient for copying 2-D blocks of data to ensure that we don't run out of available memory while copying entire large datasets.
However, there seems to be no interface in NumPy or in Python's `mmap` library to ensure that the memory-mapped file is safely closed (at least prior to Python 3.13 -- see https://github.com/python/cpython/issues/78502). This may cause issues when unwrapping a large series of interferograms in a single process, potentially leading to the number of open file descriptors exceeding the system's resource limits.
In this update, we replace usage of `numpy.memmap` with direct …

Replace memmap usage with direct file I/O

---

.github/workflows/ci.yml

Uploaded CI artifacts (including wheels and sdists) are currently used for publishing to PyPI (or TestPyPI). The `publish-to-pypi` and `publish-to-testpypi` jobs are only triggered by "push" events -- otherwise these uploaded artifacts simply go unused.
A significant portion of CI runs are triggered by PRs, which don't need these artifacts. In order to avoid wasting resources, let's upload CI artifacts only on "push" events.
We'll still continue to run the jobs which generate these artifacts for testing purposes. The artifacts will just be discarded when the job finishes.

Upload CI artifacts on "push" triggers only

---

src/snaphu/io/_raster.py
test/io/test_raster.py

The new NumPy major version makes some interface-breaking changes to the `__array__` protocol: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
The `__array__` method now must take `dtype=None` and `copy=None` parameters. Adding these parameters does not affect backwards-compatibility with older NumPy versions.
`copy=False` should always fail for `Raster`, since converting a `Raster` to an array always involves creating a new array (rather than creating a view of an existing array).
I would've preferred to make both parameters keyword-only, but the `dtype` parameter seems to be passed positionally by `np.asarray`, at least with my current NumPy version (v2.1.1), so it seems best to just allow both parameters to be positional.

Fix `io.Raster.__array__()` for NumPy>=2

---

src/snaphu/_util.py
test/test_util.py

Ensure that the scratch directory is safely deleted, even when an exception is raised during the lifetime of the context manager. Previously, when an exception was raised within the `with` block, the scratch directory cleanup step was never reached.
See https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

Ensure scratch directory is safely deleted
